# Numpy

In [33]:
import numpy as np
a=np.sin(30*3.14/180) #should 30 in radian
b=np.sin(np.deg2rad(30))
print("sin 30",a)
print("sin 30",b)
g=np.round(1.4466)
print("rounding of 1.4466",g)
g=round(1.4466,2)
print("rounding of 1.4466 to two fraction numbers only",g)
a=np.ceil(5.11)
print("ceil of number 5.11",a)
b=np.floor(5.11)
print("floor of number 5.11",b)
print("mod 11 by 2",np.mod(11,2))
print("4 pow 5",np.power(4,5))
lis=[1,2,3,4,5,6,7,8,9]
a=np.array(lis)#matrix
print("convert list to array",a)
lis=[[1,2,3],[4,5,6],[7,8,9]] 
a=np.array(lis)
print("2d array",a)
a = np.array([range(i, i + 3) for i in [2, 4, 6]]) # 2 3 4 first row etc
print("array",a)
print("empty",np.empty((3,2))) #array mn arkam so8yara awe 
a = np.random.uniform(1,10)
b = np.random.uniform(1,10,20) #20 rkam in list

print("random uniform (fraction)number",a)
print('-------------------------')
print("20 random uniform numbers",b)
print('-------------------------')
a =np.random.random((2,3))#matrix 2x3 mn 0 l 1
print("randiom fraction numbers from 0 t 1",a)
a =np.random.normal(0,1,10)  # 10 aram

print("normal random",a)# fe b negative
a =  np.random.randint(150) #rkam int

print("random int number",a)
a =np.random.randint(5, size=7)#7 arkam int

print("random int numbers",a)
a =np.random.randint(5,20, size=7)

print("random int numbers from 5 to 10",a)
a = np.random.randint(0, 10, (3, 3))

print("2d array of random int numbers",a)
# print("\n")
a = np.random.randint(5,10, size=(2, 4, 5)) #msfoften l size 4x5

print("2 2d array of random numbers",a)
a = np.random.randint(1,60,25)# 25 rkam mn 1 l 60
b = np.reshape(a,(5,5)) #y3mlha 5x5 w lzam l ab3ad ttzbt

print("random numbers",a)
print("reshape random numbers",b)
print(np.random.rand(3,2)) #msfofa mn 0 l 1

y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = np.random.choice(y)

print("random number from a list",a)
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = np.random.choice(y,size = 5)

print("5 numbers random from a list",a)
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
print("list",y)
np.random.shuffle(y)
print("list after shuffling",y)
a = np.zeros(8)
b = np.ones(10)
print("list of zeros",a)
print("list of ones",b)
a = np.zeros((3,5))
b = np.ones((6,8))

print("2d array of zeros",a)
print("2d array of ones",b)
a = np.eye(5) 
print("identity matrix",a)
a = np.full((3, 5), 35)

print("full of specific number",a)
a =np.arange(18).reshape(3,6)
b =np.arange(27).reshape(3,3,3)

print("reshape list of range",a)
print("3 2d matrix of range",b)
b =np.linspace(0,30)#default l 50 a2sm l 30 l 50 rkam
c =np.linspace(0,100,5)# a2smo l 5 kta3 mtswaya

print("line space from 0 to 30",b)
print("line space from 0 to 100",c)
b =np.linspace(0,30,12).reshape(3,4)
c =np.linspace(0,100,27).reshape(3,3,3)

print("reshape theline space",b)
print("reshape theline space",c)
a =np.diag(np.array([5,12,4,-1,3])) #in diagonal
b =np.diag(np.array([5,12,4,-1,3]),k=3)

print("array",a)
print('-------------------------')
print("array",b)
print('-------------------------')


sin 30 0.4997701026431024
sin 30 0.49999999999999994
rounding of 1.4466 1.0
rounding of 1.4466 to two fraction numbers only 1.45
ceil of number 5.11 6.0
floor of number 5.11 5.0
mod 11 by 2 1
4 pow 5 1024
convert list to array [1 2 3 4 5 6 7 8 9]
2d array [[1 2 3]
 [4 5 6]
 [7 8 9]]
array [[2 3 4]
 [4 5 6]
 [6 7 8]]
empty [[7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]]
random uniform (fraction)number 2.16148255828757
-------------------------
20 random uniform numbers [8.73117419 9.62474425 7.02678933 7.54600059 1.8079984  6.82727995
 7.65206653 4.26734224 3.39081283 2.13419073 1.61854504 4.97732612
 1.04935374 4.63134723 8.59176437 2.70283967 5.27871963 1.16526955
 7.79282792 8.79811912]
-------------------------
randiom fraction numbers from 0 t 1 [[0.90964503 0.39311755 0.06853436]
 [0.06058431 0.84781825 0.99672279]]
normal random [ 0.22542084 -0.21415332  1.04128166  0.08836365  0.36691743 -0.4434468
 -0.23674721  0.0668680

In [40]:
a = np.random.randint(0, 10, (3, 3))
b = np.count_nonzero(a)
print("array of random numbers",a)
print("count non zero elemnts in a",b)
a = np.random.randint(0, 10, (3, 3))
b = np.count_nonzero(a>5)
c = np.count_nonzero(a<8)
print("array of random numbers",a)
print("count non zero elements an >5",b)
print("count non zero elements an <8",c)
print("\n")
a = np.random.randint(0, 10, (3, 3))
b = np.count_nonzero(a>5,axis=1)
c = np.count_nonzero(a<8,axis=1)
print("array",a)
print("count non zero and >5 in each col",b)
print("count non zero and <8 in each col",c)
a = np.random.randint(0, 10, (3, 3))
b = np.any(a>5,axis=1) #or
print("array",a)
print("or each col",b)
a = np.random.randint(0, 10, (3, 3))
b =np. all(a>5)#kolhom &

print("random array",a)
print("and the array",b)

a =np.random.randint(5,20, size=9).reshape(3,3)

b = a>10 #elii as8ar mn 10 false w akbar true
c = a<15

print("array",a)
print('-------------------------')
print("array of bool",b)
print('-------------------------')
print("array of bool",c)
d=a[b] #a3rad l arkam el true
print("l true",d)
a =np.arange(9).reshape(3,3)
b =np.arange(9).reshape(3,3)
c = 2*b
d = np.isclose(a,b,rtol = 0.1)# el far2 benhom .1 mokrnat l matrix
e = np.isclose(a,c,rtol = 0.1)


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print("difference till .1",d)
print('-------------------------')
print("difference till .1",e)
a =np.arange(5)
b =np.empty(5)

np.multiply(a, 10, out=b) #scaler multiplication w a7ot l nateg fe b

print(a)
print("scaler multipication",b)


array of random numbers [[8 7 7]
 [8 9 3]
 [1 5 4]]
count non zero elemnts in a 9
array of random numbers [[1 9 7]
 [3 3 6]
 [6 5 0]]
count non zero elements an >5 4
count non zero elements an <8 8


array [[3 8 4]
 [4 5 9]
 [6 0 6]]
count non zero and >5 in each col [1 1 2]
count non zero and <8 in each col [2 2 3]
array [[0 0 7]
 [8 5 6]
 [3 9 9]]
or each col [ True  True  True]
random array [[5 8 9]
 [9 7 3]
 [2 8 2]]
and the array False
array [[16 15 12]
 [14 14  7]
 [ 5 14  9]]
-------------------------
array of bool [[ True  True  True]
 [ True  True False]
 [False  True False]]
-------------------------
array of bool [[False False  True]
 [ True  True  True]
 [ True  True  True]]
l true [16 15 12 14 14 14]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------------------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
-------------------------
difference till .1 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
-----------------------

In [2]:
a =arange(5)
b =empty(5)
multiply(a, 10, out=b) #scaler multiplication w a7ot l nateg fe b

print(a)
print(b)
a =arange(5)
b =empty(5) #array kolha zeros
print("\n")
power(a, 4, out=b) #tare2at lpower

print(a)
print(b)
print("\n")
a =arange(15)


b = add.reduce(a) #agm3hom kolhom elii fe row

print(a)
print(b)
print("\n")
a =arange(2,8)


b = multiply.reduce(a)#adrab kol eli fe row

print(a)
print(b)
print("\n")
a =arange(2,8)


b = multiply.outer(a,a) # a3ml array a*a kol row mdrob fe rkam

print(a)
print(b)
print("\n")
a =arange(10)


b = add.accumulate(a) #kol rkam fe row mgmo3 3lakol eli 2ablo

print(a)
print(b)
print("\n")
a =arange(2,8)


b = multiply.accumulate(a) #kol rkam fe row mdrob fe eli 2alpo factorial

print(a)
print(b)
print("\n len")
a =arange(12)
b = len(a) #12

c = a.reshape(3,4)
d = len(c)#no of rows

print(a)
print(b)
print(c)
print(d)
print("\n")
a =arange(12)
b = a.size #12

c = a.reshape(3,4)
d = c.size #12

print(a)
print(b)
print(c)
print(d)
print("\n")
a =arange(12)
b = a.shape #ygeb kam xkam

c = a.reshape(3,4)
d = c.shape

print(a)
print(b)
print(c)
print(d)
print("\n")
a =arange(12)
b = a.ndim #ygeb ldimensions ad eh

c = a.reshape(3,4)
d = c.ndim

print(a)
print(b)
print(c)
print(d)
print("\n")
a =array(['a','d','g','h','j'])
b = a.dtype #no3o eh

c = arange(12)
d = c.reshape(3,4)
e = d.dtype

print(a)
print(b)
print(c)
print(d)
print(e)
#reshape b tre2a tanya
a = matrix('{} {} ; {} {}'.format(1,2,3,4))
b = matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6))

print(a)
print(b)
a =arange(9)
b = a.reshape(3,3)
c = trace(b)#agma3 diagonal bs


print(a)
print(b)
print(c)
a =arange(9)
b = a.reshape(3,3)
c = linalg.det(b) #kemat matrix
d = linalg.eig(b)


print(a)
print(b)
print(c)
print(d)
a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print(c)
print(d)
print(e)
print(f)
print(g)


NameError: name 'arange' is not defined

In [41]:
a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print(c)
print(d)
print(e)
print(f)
print(g)
print("\n")
a =arange(36).reshape(6,6)

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)
print("\n")
a =arange(36).reshape(6,6)

c = a[3,1]
d = a[3,:]
e = a[:,2]
f = a[:,1:3]
g = a[1:2,:]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)


[0 1 2 3 4 5 6 7 8 9]
3
[3 4 5 6 7 8]
[3 5 7]
9
7


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
-------------------------
[30 31 32 33 34 35]
-------------------------
[18 19 20 21 22 23]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
19
-------------------------
[18 19 20 21 22 23]
-------------------------
[ 2  8 14 20 26 32]
-------------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
-------------------------
[[ 6  7  8  9 10 11]]


In [2]:
from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a*3#darb 3adi
d = b/5

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = sin(a)
d = b**2
e = log(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
a =random.randint(1,4, size=9).reshape(3,3)
b =random.randint(1,4, size=9).reshape(3,3)


c = dot(a,b)#dot mult saf fe 3amod

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
a =random.randint(5,20, size=9).reshape(3,3)
b = sum(a)
c = a.sum()
d = a.sum(axis = 1)
e = a.sum(axis = 0)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
a =random.randint(5,20, size=9).reshape(3,3)
b = a.mean()
c = a.std()
d = a.var()

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
a =random.randint(5,20, size=9).reshape(3,3)
b = corrcoef(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
a =random.randint(5,20, size=9).reshape(3,3)
b = sort(a,axis=0)
c = sort(a,axis=1)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
a =random.randint(1,4, size=9).reshape(3,3)
b =linalg.inv(a)

c = dot(a,b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)


[[11  9 13]
 [ 6 12 10]
 [ 8 14 10]]
-------------------------
[[10  6 17]
 [ 7  5  7]
 [11 19 15]]
-------------------------
[[33 27 39]
 [18 36 30]
 [24 42 30]]
-------------------------
[[2.  1.2 3.4]
 [1.4 1.  1.4]
 [2.2 3.8 3. ]]
[[13 13  7]
 [ 6 16  6]
 [18 14 19]]
-------------------------
[[17 14  9]
 [ 9  7 14]
 [14 14 11]]
-------------------------
[[ 0.42016704  0.42016704  0.6569866 ]
 [-0.2794155  -0.28790332 -0.2794155 ]
 [-0.75098725  0.99060736  0.14987721]]
-------------------------
[[289 196  81]
 [ 81  49 196]
 [196 196 121]]
[[1 1 1]
 [3 3 3]
 [3 1 3]]
-------------------------
[[1 3 1]
 [2 2 1]
 [3 3 1]]
-------------------------
[[ 6  8  3]
 [18 24  9]
 [14 20  7]]
[[ 7 15  9]
 [15 13 16]
 [17 18  9]]
-------------------------
119
-------------------------
119
-------------------------
[31 44 44]
-------------------------
[39 46 34]
[[18 19 14]
 [11 14 18]
 [10  9 11]]
-------------------------
13.777777777777779
-------------------------
3.5832256659104664
------

# numpy with files

In [7]:
fname = 'merna.txt'
dtype1 = dtype([('gender', '|S1'), ('height', 'f8')])
a = loadtxt(fname, dtype=dtype1, skiprows=9, usecols=(1,3))
 
print(a)
a,b,c = loadtxt('fil.txt', unpack=True,skiprows=3)
print(a)
print(b)
print(c)
data = genfromtxt('fil2.txt', skip_header=1,
                  dtype=[('student','u8'),
                         ('gender','S1'),('black','f8'),
                         ('colour','f8')],delimiter=',',
                         missing_values='X')

print(data)


[(b'M', 1.82) (b'M', 1.77) (b'F', 1.68) (b'M', 1.72) (b'F', 1.78)
 (b'F', 1.6 ) (b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64)
 (b'M', 1.63) (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 )
 (b'M', 1.97) (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]
[1890. 1900. 1910. 1920. 1930.]
[26.1 25.9 25.1 24.6 24.3]
[22.  21.9 21.6 21.2 21.3]
[(1, b'F', 18.72, 31.11) (2, b'F', 21.14, 52.47) (3, b'F', 19.38, 33.9 )]


# Polynomial

In [11]:
import numpy as np

Polynomial = np.polynomial.Polynomial

X= np.array([0,20,40,60,80,100,120,140,160,180])
Y= np.array([10,9,8,7,6,5,4,3,2,1])

points,stats = Polynomial.fit(X,Y,1,full=True) #y study w ygeb best fit w aktab l degree bta3ha

print(points)
#azayaktab lmo3dla
a = poly1d((-7))
b = poly1d((-7,2))
c = poly1d((-7,2,1))
d = poly1d((-7,2,1,3))
e = poly1d((-7,2,1,3,6))


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
#azay a3wad feha
a = poly1d((-7,2,1,3,6))

b=a(5)
c=a(0)
d=a(-15)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
#ktaba w t3wed m3 b3d
a = polyval((1,2),2)
b = polyval((1,2,3),7)
c = polyval((1,2,3,5),-3)
d = polyval((1,2,3,5,-6),12.6)


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
#derivative
a =polyder(poly1d((1,2,3)))
b =polyder(poly1d((1,2,3)),2)
c =polyder(poly1d((1,2,3)),3)# 3 kam mara

d =polyder(poly1d((1,2,3,5,12)))
e =polyder(poly1d((1,2,3,5,12)),3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
a =polyder(poly1d((1,2,3)))
b =polyder(poly1d((1,2,3)),2)
c =polyder(poly1d((1,2,3)),3)

d =polyder(poly1d((1,2,3,5,12)))
e =polyder(poly1d((1,2,3,5,12)),3)

print(a(2))
print('-------------------------')
print(b(0)) #a3wad fe ashtkak
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))
#integration
a =polyint(poly1d((1,2,3)))
b =polyint(poly1d((1,2,3)),2)
c =polyint(poly1d((1,2,3)),3)

d =polyint(poly1d((1,2,3,5,12)))
e =polyint(poly1d((1,2,3,5,12)),3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
a =polyint(poly1d((1,2,3)))
b =polyint(poly1d((1,2,3)),2)
c =polyint(poly1d((1,2,3)),3)

d =polyint(poly1d((1,2,3,5,12)))
e =polyint(poly1d((1,2,3,5,12)),3)

print(a(2))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))
#roots l equation elii y5leha 0
a =roots(poly1d((1,2)))
b =roots(poly1d((1,2,3)))
c =roots(poly1d((1,2,3,5)))
d =roots(poly1d((1,2,3,5,12)))
e =roots(poly1d((1,2,3,5,12,22)))


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
#zy l fit
x = array([3,6,2,5,4])
y = array([2,3,-9,6,2.5])
z = polyfit(x, y, 2)


print(x)
print('-------------------------')
print(y)
print('-------------------------')
print(z)
print('-------------------------')


poly([ 5.5 -4.5])
 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
-------------------------
-4079
-------------------------
6
-------------------------
-360939
4
-------------------------
66
-------------------------
-13
-------------------------
29738.769599999992
 
2 x + 2
-------------------------
 
2
-------------------------
 
0
-------------------------
   3     2
4 x + 6 x + 6 x + 5
-------------------------
 
24 x + 12
6
-------------------------
2
-------------------------
0.0
-------------------------
1
-------------------------
132
        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
-------------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 2.5 x + 12 x
-------