# Numpy

In [33]:
from numpy import *
a=sin(30*3.14/180)
b=sin(deg2rad(30))
print(a)
print(b)
g=round(1.4466)
print(g)
g=round(1.4466,2)
print(g)
a=ceil(5.11)
print(a)
b=floor(5.11)
print(b)
print(mod(11,2))
print(pow(4,5))
lis=[1,2,3,4,5,6,7,8,9]
a=array(lis)#matrix
print(a)
lis=[[1,2,3],[4,5,6],[7,8,9]]
a=array(lis)
print(a)
a = array([range(i, i + 3) for i in [2, 4, 6]])

print(a)
print("\n")
print(empty((3,2)))
a = random.uniform(1,10)
b = random.uniform(1,10,20) #20 rkam in list

print(a)
print('-------------------------')
print(b)
print('-------------------------')
a =random.random((2,3))#mn 0 l 1
print(a)
a =random.normal(0,1,10)

print(a)
a =  random.randint(150) #rkam int

print(a)
a =random.randint(5, size=7)#7 arkam int

print(a)
a =random.randint(5,20, size=7)

print(a)
a = random.randint(0, 10, (3, 3))

print(a)
print("\n")
a = random.randint(5,10, size=(2, 4, 5)) #msfoften l size 4x5

print(a)
a = random.randint(1,60,25)
b = reshape(a,(5,5)) #y3mlha 5x5 w lzam l ab3ad ttzbt

print(a)
print(b)
print(random.rand(3,2)) #msfofa mn 0 l 1

y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y)

print(a)
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
a = random.choice(y,size = 5)

print(a)
y=[1,2,3,6,9,8,5,4,7,8,9,6,5,9,6]
print(y)

random.shuffle(y)
a = zeros(8)
b = ones(10)

print(a)
print(b)
a = zeros((3,5))
b = ones((6,8))

print(a)
print(b)
a = eye(5) 
print(a)
a = full((3, 5), 35)

print(a)
a =arange(18).reshape(3,6)
b =arange(27).reshape(3,3,3)

print(a)
print(b)
b =linspace(0,30)#default l 50
c =linspace(0,100,5)# a2smo l 5 kta3 mtswaya

print(b)
print(c)
b =linspace(0,30,12).reshape(3,4)
c =linspace(0,100,27).reshape(3,3,3)

print(b)
print(c)
a =diag(array([5,12,4,-1,3]))
b =diag(array([5,12,4,-1,3]),k=3)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a)


print(a)
print(b)
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a>5)
c = count_nonzero(a<8)

print(a)
print(b)
print(c)
print("\n")
a = random.randint(0, 10, (3, 3))
b = count_nonzero(a>5,axis=1)
c = count_nonzero(a<8,axis=1)

print(a)
print(b)
print(c)
a = random.randint(0, 10, (3, 3))
b = any(a>5,axis=1) #or
print(a)
print(b)
a = random.randint(0, 10, (3, 3))
b = all(a>5)#kolhom &

print(a)
print(b)

a =random.randint(5,20, size=9).reshape(3,3)

b = a>10 #elii as8ar mn 10 false w akbar true
c = a<15

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
d=a[b] #a3rad l arkam el true
print(d)
a =arange(9).reshape(3,3)
b =arange(9).reshape(3,3)
c = 2*b
d = isclose(a,b,rtol = 0.1)# el far2 benhom .1 mokrnat l matrix
e = isclose(a,c,rtol = 0.1)


print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
a =arange(5)
b =empty(5)

multiply(a, 10, out=b) #scaler multiplication w a7ot l nateg fe b

print(a)
print(b)


0.4997701026431024
0.49999999999999994
1
1.45
6.0
5.0
1
1024
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


[[7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304]]
9.142607317627498
-------------------------
[3.7148057  1.47099439 8.79525072 2.28616444 2.75537673 3.02951482
 4.70615305 2.62680437 4.13295856 4.25072573 7.8011098  9.71141854
 3.93132365 2.90304237 3.22376169 8.1201614  1.29377528 6.00836546
 9.00143278 4.31143322]
-------------------------
[[0.55390619 0.60887751 0.2901526 ]
 [0.57001767 0.1293802  0.14233395]]
[ 0.96697668  0.52460192  0.41303016 -0.10325558  0.31810263  0.30665618
 -0.96479827  0.19594313  1.58143572  0.20936271]
129
[2 0 0 4 4 4 1]
[ 5  9 12  6 19 19 15]
[[8 8 5]
 [1 9 2]
 [8 9 8]]


[[[9 6 8 9 6]
  [7 6 5 8 6]
  [7 5 5 7 6]
  [5 9 5 6 5]]

 [[6 6 8 8 5]
  [8 8 9 5 9]
  [6 8 8 5 7]
  [5 9 6 9 6]]]
[18 47 22 18 10 15  2 46 23 50 50 31 45 55 48 26 28 45  2 11  1 42 44 47
 3

In [40]:
a =arange(5)
b =empty(5)
multiply(a, 10, out=b) #scaler multiplication w a7ot l nateg fe b

print(a)
print(b)
a =arange(5)
b =empty(5) #array kolha zeros
print("\n")
power(a, 4, out=b) #tare2at lpower

print(a)
print(b)
print("\n")
a =arange(15)


b = add.reduce(a) #agm3hom kolhom elii fe row

print(a)
print(b)
print("\n")
a =arange(2,8)


b = multiply.reduce(a)#adrab kol eli fe row

print(a)
print(b)
print("\n")
a =arange(2,8)


b = multiply.outer(a,a) # a3ml array a*a kol row mdrob fe rkam

print(a)
print(b)
print("\n")
a =arange(10)


b = add.accumulate(a) #kol rkam fe row mgmo3 3lakol eli 2ablo

print(a)
print(b)
print("\n")
a =arange(2,8)


b = multiply.accumulate(a) #kol rkam fe row mdrob fe eli 2alpo factorial

print(a)
print(b)
print("\n len")
a =arange(12)
b = len(a) #12

c = a.reshape(3,4)
d = len(c)#no of rows

print(a)
print(b)
print(c)
print(d)
print("\n")
a =arange(12)
b = a.size #12

c = a.reshape(3,4)
d = c.size #12

print(a)
print(b)
print(c)
print(d)
print("\n")
a =arange(12)
b = a.shape #ygeb kam xkam

c = a.reshape(3,4)
d = c.shape

print(a)
print(b)
print(c)
print(d)
print("\n")
a =arange(12)
b = a.ndim #ygeb ldimensions ad eh

c = a.reshape(3,4)
d = c.ndim

print(a)
print(b)
print(c)
print(d)
print("\n")
a =array(['a','d','g','h','j'])
b = a.dtype #no3o eh

c = arange(12)
d = c.reshape(3,4)
e = d.dtype

print(a)
print(b)
print(c)
print(d)
print(e)
#reshape b tre2a tanya
a = matrix('{} {} ; {} {}'.format(1,2,3,4))
b = matrix('{} {} {};{} {} {}'.format(1,2,3,4,5,6))

print(a)
print(b)
a =arange(9)
b = a.reshape(3,3)
c = trace(b)#agma3 diagonal bs


print(a)
print(b)
print(c)
a =arange(9)
b = a.reshape(3,3)
c = linalg.det(b) #kemat matrix
d = linalg.eig(b)


print(a)
print(b)
print(c)
print(d)
a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print(c)
print(d)
print(e)
print(f)
print(g)


[0 1 2 3 4]
[ 0. 10. 20. 30. 40.]


[0 1 2 3 4]
[  0.   1.  16.  81. 256.]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105


[2 3 4 5 6 7]
5040


[2 3 4 5 6 7]
[[ 4  6  8 10 12 14]
 [ 6  9 12 15 18 21]
 [ 8 12 16 20 24 28]
 [10 15 20 25 30 35]
 [12 18 24 30 36 42]
 [14 21 28 35 42 49]]


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]


[2 3 4 5 6 7]
[   2    6   24  120  720 5040]

 len
[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3


[ 0  1  2  3  4  5  6  7  8  9 10 11]
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


['a' 'd' 'g' 'h' 'j']
<U1
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
int32
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [41]:
a =arange(10) 

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print(c)
print(d)
print(e)
print(f)
print(g)
print("\n")
a =arange(36).reshape(6,6)

c = a[3]
d = a[3:9]
e = a[3:9:2]
f = a[-1]
g = a[-3]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)
print("\n")
a =arange(36).reshape(6,6)

c = a[3,1]
d = a[3,:]
e = a[:,2]
f = a[:,1:3]
g = a[1:2,:]

print(a)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
print('-------------------------')
print(f)
print('-------------------------')
print(g)


[0 1 2 3 4 5 6 7 8 9]
3
[3 4 5 6 7 8]
[3 5 7]
9
7


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[18 19 20 21 22 23]
-------------------------
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
[[18 19 20 21 22 23]
 [30 31 32 33 34 35]]
-------------------------
[30 31 32 33 34 35]
-------------------------
[18 19 20 21 22 23]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
-------------------------
19
-------------------------
[18 19 20 21 22 23]
-------------------------
[ 2  8 14 20 26 32]
-------------------------
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]
 [25 26]
 [31 32]]
-------------------------
[[ 6  7  8  9 10 11]]


In [2]:
from numpy import *
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = a*3#darb 3adi
d = b/5

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
a =random.randint(5,20, size=9).reshape(3,3)
b =random.randint(5,20, size=9).reshape(3,3)
c = sin(a)
d = b**2
e = log(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
a =random.randint(1,4, size=9).reshape(3,3)
b =random.randint(1,4, size=9).reshape(3,3)


c = dot(a,b)#dot mult saf fe 3amod

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
a =random.randint(5,20, size=9).reshape(3,3)
b = sum(a)
c = a.sum()
d = a.sum(axis = 1)
e = a.sum(axis = 0)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)
a =random.randint(5,20, size=9).reshape(3,3)
b = a.mean()
c = a.std()
d = a.var()

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
a =random.randint(5,20, size=9).reshape(3,3)
b = corrcoef(a)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
a =random.randint(5,20, size=9).reshape(3,3)
b = sort(a,axis=0)
c = sort(a,axis=1)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
a =random.randint(1,4, size=9).reshape(3,3)
b =linalg.inv(a)

c = dot(a,b)

print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)


[[11  9 13]
 [ 6 12 10]
 [ 8 14 10]]
-------------------------
[[10  6 17]
 [ 7  5  7]
 [11 19 15]]
-------------------------
[[33 27 39]
 [18 36 30]
 [24 42 30]]
-------------------------
[[2.  1.2 3.4]
 [1.4 1.  1.4]
 [2.2 3.8 3. ]]
[[13 13  7]
 [ 6 16  6]
 [18 14 19]]
-------------------------
[[17 14  9]
 [ 9  7 14]
 [14 14 11]]
-------------------------
[[ 0.42016704  0.42016704  0.6569866 ]
 [-0.2794155  -0.28790332 -0.2794155 ]
 [-0.75098725  0.99060736  0.14987721]]
-------------------------
[[289 196  81]
 [ 81  49 196]
 [196 196 121]]
[[1 1 1]
 [3 3 3]
 [3 1 3]]
-------------------------
[[1 3 1]
 [2 2 1]
 [3 3 1]]
-------------------------
[[ 6  8  3]
 [18 24  9]
 [14 20  7]]
[[ 7 15  9]
 [15 13 16]
 [17 18  9]]
-------------------------
119
-------------------------
119
-------------------------
[31 44 44]
-------------------------
[39 46 34]
[[18 19 14]
 [11 14 18]
 [10  9 11]]
-------------------------
13.777777777777779
-------------------------
3.5832256659104664
------